### PR TITLE
Only depend on mypy.api

### LINKED ISSUE #6: required argument 'flush_errors' error with latest version of mypy
Hi @dbader,

`pytest-mypy` seems to be broken with the latest release of `mypy==0.570`, but I did not yet have the time to investigate it further or fix it. It yields the following errors for each file:

```
[...]: in runtest
    res = mypy.main.type_check_only(sources, None, options)
E   TypeError: type_check_only() missing 1 required positional argument: 'flush_errors'
```

### PR DESCRIPTION
**Pull request by dmtucker**
Fixes #6 

> I think we should strongly discourage such use of interfaces internal to mypy. The only public APIs are the command line and the mypy.api module.
https://github.com/python/mypy/issues/4681#issuecomment-371037599

### CODE REVIEW

**Comment by dmtucker** [comment]
I hit the same Python 3.3 failure as @petr-muller:
https://travis-ci.org/dbader/pytest-mypy/jobs/350216845

**Comment by petr-muller** [comment]
Yup, this looks even better!

**Comment by dmtucker** [comment]
Another data point for dropping Python 3.3:
```
| python_version | download_count |
| -------------- | -------------- |
| 3.6            |          9,940 |
| None           |          5,010 |
| 3.5            |            941 |
| 3.4            |            443 |
| 1.17           |            267 |
| 2.7            |            157 |
| 3.7            |             62 |
| 3.3            |              4 |
```
There have been very few 3.3 downloads in the last year.
(Produced with `pypinfo --days 365 pytest-mypy pyversion`)

**Comment by dbader** [comment]
Thanks! LGTM :-) If anybody helps with maintaining & possibly growing this project ping me and I'll add you as a collaborator. I've got too much on my plate right now and I'm not doing a good job at supporting this project.

**Comment by dmtucker** [comment]
@dbader I'd be interested (more for maintenance than dev, but hey, who knows).

#9 is another option.

**Comment by dbader** [comment]
Hey @dmtucker, just sent you an invite to add you as a collaborator :-)

**Pull request merged**
