### PR TITLE
Bump the version to 0.3.1

### LINKED ISSUE #16: Publish master to PyPI
Hi, @dbader, thanks for the great plugin!

I wonder if it would be possible to publish the master branch to PyPI, as [this statement](https://github.com/dbader/pytest-mypy/blob/809d68ab13c959a589c557ae6f6134cf6fb81043/pytest_mypy.py#L58) breaks on new versions of mypy (somewhere around v.0.580 I think). The [new function signature](https://github.com/python/mypy/blob/7519e89ae8054ea3f22c4d13f16aaf9ae8f10f0a/mypy/main.py#L127) of ``mypy.main::type_check_only()`` has changed, and it seems to have been fixed by [this commit](https://github.com/dbader/pytest-mypy/commit/1958f97c6bb4e2b86a1767433974f65e2da6b293).

Thanks in advance!

### PR DESCRIPTION
**Pull request by dmtucker**
Closes #16 

This will allow us to release the fix for #6.

@dbader, I suspect you'll have to do the actual upload.

### CODE REVIEW

**Comment by dmtucker** [comment]
We may want to include #12.

**Comment by dmtucker** [comment]
@dbader If we hook up [automatic deployment to PyPI through Travis](https://docs.travis-ci.com/user/deployment/pypi/#Deploying-tags), I can probably cut releases by pushing tags.

**Comment by dmtucker** [comment]
Altogether, this release includes:

Run with just --mypy-ignore-missing-imports
#17 by dmtucker was merged 3 minutes ago 0.3.1

Define a header for the test report
#15 by dmtucker was merged 38 minutes ago 0.3.1

Added --mypy-ignore-missing-imports flag
#13 by mmasztalerczuk was merged 18 minutes ago 0.3.1

Invoke mypy with --incremental
#12 by dmtucker was merged 38 minutes ago 0.3.1

Only depend on mypy.api
#8 by dmtucker was merged on Mar 16 0.3.1

**Comment by lambdalisue** [comment]
Thank you!

**Pull request merged**
